# A generic, single database configuration.

[alembic]
# path to migration script directory
script_location = alembic

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# file_template = %%(rev)s_%%(slug)s

# max length of characters in file_template
# truncate_slug_length = 40

# timezone to use when rendering the date within the migration file as
# well as the filename.
# string value, e.g. "UTC"
timezone = UTC

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

[post_write_hooks]

[logging]
default_handler = console

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
